version: '3.7'

services:
  mongodb:
    image: mongo:latest
    volumes:
      - data:/data/db
    ports:
      - '27017:27017'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=someuser
      - MONGO_INITDB_ROOT_PASSWORD=somepassword
      - COLLECTION=routes
      - DB_NAME=json_storage

  ts-node-docker:
    depends_on: 
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    restart: on-failure
    volumes:
      - ./src:/app/src
    container_name: ts-node-docker
    ports:
      - '3000:3000'
    external_links:
      - mongo
    environment:
      - PORT=3000
      - CLIENT_STR=mongo+srv://someuser:somepassword@mongodb:27017/json_storage
  
volumes:
  data: