export type ObjectRate = {
  BTC: number;
  ETH: number;
  USDT: number;
  USDC: number;
  BNB: number;
  BUSD: number;
  XRP: number;
  ADA: number;
  SOL: number;
  DOT: number;
  SHIB: number;
  TRX: number;
  AVAX: number;
  MATIC: number;
  WBTC: number;
  LTC: number;
  FTT: number;
  CRO: number;
  LINK: number;
  XLM: number;
  NEAR: number;
};
